// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DownloadTaskDto {
  final PlatformInt64 id;
  final PlatformInt64 illustId;
  final String illustTitle;
  final int pageIndex;
  final int pageCount;
  final String url;
  final String targetPath;
  final String saveTarget;
  final String status;
  final int progress;
  final String errorMessage;
  final int retryCount;
  final PlatformInt64 createdTime;
  final PlatformInt64 updatedTime;

  const DownloadTaskDto({
    required this.id,
    required this.illustId,
    required this.illustTitle,
    required this.pageIndex,
    required this.pageCount,
    required this.url,
    required this.targetPath,
    required this.saveTarget,
    required this.status,
    required this.progress,
    required this.errorMessage,
    required this.retryCount,
    required this.createdTime,
    required this.updatedTime,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      illustId.hashCode ^
      illustTitle.hashCode ^
      pageIndex.hashCode ^
      pageCount.hashCode ^
      url.hashCode ^
      targetPath.hashCode ^
      saveTarget.hashCode ^
      status.hashCode ^
      progress.hashCode ^
      errorMessage.hashCode ^
      retryCount.hashCode ^
      createdTime.hashCode ^
      updatedTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadTaskDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          illustId == other.illustId &&
          illustTitle == other.illustTitle &&
          pageIndex == other.pageIndex &&
          pageCount == other.pageCount &&
          url == other.url &&
          targetPath == other.targetPath &&
          saveTarget == other.saveTarget &&
          status == other.status &&
          progress == other.progress &&
          errorMessage == other.errorMessage &&
          retryCount == other.retryCount &&
          createdTime == other.createdTime &&
          updatedTime == other.updatedTime;
}

class UiCurrentUser {
  final PlatformInt64 userId;
  final String name;
  final String account;
  final String profileImageUrl;
  final bool isPremium;

  const UiCurrentUser({
    required this.userId,
    required this.name,
    required this.account,
    required this.profileImageUrl,
    required this.isPremium,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      name.hashCode ^
      account.hashCode ^
      profileImageUrl.hashCode ^
      isPremium.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiCurrentUser &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          name == other.name &&
          account == other.account &&
          profileImageUrl == other.profileImageUrl &&
          isPremium == other.isPremium;
}

class UiIllustRankQuery {
  final String mode;
  final String date;

  const UiIllustRankQuery({required this.mode, required this.date});

  @override
  int get hashCode => mode.hashCode ^ date.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiIllustRankQuery &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          date == other.date;
}

class UiIllustSearchQuery {
  final String word;
  final String searchTarget;
  final String sort;

  const UiIllustSearchQuery({
    required this.word,
    required this.searchTarget,
    required this.sort,
  });

  @override
  int get hashCode => word.hashCode ^ searchTarget.hashCode ^ sort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiIllustSearchQuery &&
          runtimeType == other.runtimeType &&
          word == other.word &&
          searchTarget == other.searchTarget &&
          sort == other.sort;
}

class UiLoginByCodeQuery {
  final String code;
  final String verify;

  const UiLoginByCodeQuery({required this.code, required this.verify});

  @override
  int get hashCode => code.hashCode ^ verify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiLoginByCodeQuery &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          verify == other.verify;
}
