// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class UiIllustRankQuery {
  final String mode;
  final String date;

  const UiIllustRankQuery({required this.mode, required this.date});

  @override
  int get hashCode => mode.hashCode ^ date.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiIllustRankQuery &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          date == other.date;
}

class UiIllustSearchQuery {
  final String mode;
  final String word;

  const UiIllustSearchQuery({required this.mode, required this.word});

  @override
  int get hashCode => mode.hashCode ^ word.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiIllustSearchQuery &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          word == other.word;
}

class UiLoginByCodeQuery {
  final String code;
  final String verify;

  const UiLoginByCodeQuery({required this.code, required this.verify});

  @override
  int get hashCode => code.hashCode ^ verify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiLoginByCodeQuery &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          verify == other.verify;
}
