// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../pixirust/entities.dart';
import '../udto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_execute_single_download`, `block_on`

Future<String> desktopRoot() => RustLib.instance.api.crateApiApiDesktopRoot();

Future<void> init({required String root}) =>
    RustLib.instance.api.crateApiApiInit(root: root);

Future<void> saveProperty({required String k, required String v}) =>
    RustLib.instance.api.crateApiApiSaveProperty(k: k, v: v);

Future<String> loadProperty({required String k}) =>
    RustLib.instance.api.crateApiApiLoadProperty(k: k);

Future<void> copyImageTo({required String srcPath, required String toDir}) =>
    RustLib.instance.api.crateApiApiCopyImageTo(srcPath: srcPath, toDir: toDir);

Future<void> setInChina({required bool value}) =>
    RustLib.instance.api.crateApiApiSetInChina(value: value);

Future<bool> getInChina() => RustLib.instance.api.crateApiApiGetInChina();

Future<void> perInChina() => RustLib.instance.api.crateApiApiPerInChina();

Future<bool> preLogin() => RustLib.instance.api.crateApiApiPreLogin();

Future<LoginUrl> createLoginUrl() =>
    RustLib.instance.api.crateApiApiCreateLoginUrl();

Future<bool> loginByCode({required UiLoginByCodeQuery query}) =>
    RustLib.instance.api.crateApiApiLoginByCode(query: query);

Future<LoginUrl> createRegisterUrl() =>
    RustLib.instance.api.crateApiApiCreateRegisterUrl();

Future<String> requestUrl({required String params}) =>
    RustLib.instance.api.crateApiApiRequestUrl(params: params);

Future<IllustResponse> illustFromUrl({required String url}) =>
    RustLib.instance.api.crateApiApiIllustFromUrl(url: url);

Future<UserPreviewsResponse> userPreviewsFromUrl({required String url}) =>
    RustLib.instance.api.crateApiApiUserPreviewsFromUrl(url: url);

Future<String> illustRecommendedFirstUrl() =>
    RustLib.instance.api.crateApiApiIllustRecommendedFirstUrl();

Future<String> illustSearchFirstUrl({required UiIllustSearchQuery query}) =>
    RustLib.instance.api.crateApiApiIllustSearchFirstUrl(query: query);

Future<String> illustRankFirstUrl({required UiIllustRankQuery query}) =>
    RustLib.instance.api.crateApiApiIllustRankFirstUrl(query: query);

Future<String> userIllustsFirstUrl({required PlatformInt64 userId}) =>
    RustLib.instance.api.crateApiApiUserIllustsFirstUrl(userId: userId);

Future<IllustTrendingTags> illustTrendingTags() =>
    RustLib.instance.api.crateApiApiIllustTrendingTags();

Future<String> illustTrendingTagsUrl() =>
    RustLib.instance.api.crateApiApiIllustTrendingTagsUrl();

/// 下载pixiv的图片
Future<String> loadPixivImage({required String url}) =>
    RustLib.instance.api.crateApiApiLoadPixivImage(url: url);

Future<UserDetail> userDetail({required PlatformInt64 userId}) =>
    RustLib.instance.api.crateApiApiUserDetail(userId: userId);

Future<void> followUser({
  required PlatformInt64 userId,
  required String restrict,
}) => RustLib.instance.api.crateApiApiFollowUser(
  userId: userId,
  restrict: restrict,
);

Future<void> unfollowUser({required PlatformInt64 userId}) =>
    RustLib.instance.api.crateApiApiUnfollowUser(userId: userId);

Future<UserPreviewsResponse> userFollowing({
  required PlatformInt64 userId,
  required String restrict,
}) => RustLib.instance.api.crateApiApiUserFollowing(
  userId: userId,
  restrict: restrict,
);

Future<IllustResponse> userBookmarks({
  required PlatformInt64 userId,
  required String restrict,
  String? tag,
}) => RustLib.instance.api.crateApiApiUserBookmarks(
  userId: userId,
  restrict: restrict,
  tag: tag,
);

Future<PlatformInt64> createDownloadTask({
  required PlatformInt64 illustId,
  required String illustTitle,
  required int pageIndex,
  required int pageCount,
  required String url,
  required String targetPath,
  required String saveTarget,
}) => RustLib.instance.api.crateApiApiCreateDownloadTask(
  illustId: illustId,
  illustTitle: illustTitle,
  pageIndex: pageIndex,
  pageCount: pageCount,
  url: url,
  targetPath: targetPath,
  saveTarget: saveTarget,
);

Future<List<DownloadTaskDto>> getAllDownloadTasks() =>
    RustLib.instance.api.crateApiApiGetAllDownloadTasks();

Future<List<DownloadTaskDto>> getPendingDownloadTasks() =>
    RustLib.instance.api.crateApiApiGetPendingDownloadTasks();

Future<void> updateDownloadTaskStatus({
  required PlatformInt64 id,
  required String status,
  required int progress,
  required String errorMessage,
}) => RustLib.instance.api.crateApiApiUpdateDownloadTaskStatus(
  id: id,
  status: status,
  progress: progress,
  errorMessage: errorMessage,
);

Future<void> retryDownloadTask({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiApiRetryDownloadTask(id: id);

Future<void> deleteDownloadTask({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiApiDeleteDownloadTask(id: id);

Future<void> deleteCompletedDownloadTasks() =>
    RustLib.instance.api.crateApiApiDeleteCompletedDownloadTasks();

Future<void> executeDownloadTask({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiApiExecuteDownloadTask(id: id);
